Add ServiceMonitor for cloudflared
STRRL/cloudflare-tunnel-ingress-controller pull request #129
Opened 2024-10-08 15:45 UTC by z0rc

Resolves #127

2024-10-08 18:53 UTC, z0rc commented on .gitignore
> +/cloudflare-tunnel-ingress-controller
Ignore binary only at root level. Otherwise git ignores new files in `helm/cloudflare-tunnel-ingress-controller` and other directories.

2024-10-09 17:58 UTC, STRRL commented
Thanks for your contribution! @z0rc I will review this PR and push it to get merged soon! ❤️

2024-10-11 14:48 UTC, z0rc commented on helm/cloudflare-tunnel-ingress-controller/templates/controlled-cloudflared-connector-headless-service.yaml
> +    strrl.dev/cloudflare-tunnel-ingress-controller: controlled-cloudflared-connector
This selector doesn't work btw. `controlled-cloudflared-connector` pods don't have this label, it's set only Deployment metadata, which doesn't propagate to pod spec.

2024-10-16 23:18 UTC, STRRL commented on helm/cloudflare-tunnel-ingress-controller/templates/controlled-cloudflared-connector-headless-service.yaml
> +    strrl.dev/cloudflare-tunnel-ingress-controller: controlled-cloudflared-connector
🤔 I forget to apply this label on the podtempalte when I create controlled cloudflare connector template.

I would fix it soon.

2024-10-17 03:16 UTC, STRRL requested changes
rest LGTM! thanks! @z0rc

2024-10-17 03:16 UTC, STRRL commented on helm/cloudflare-tunnel-ingress-controller/templates/controlled-cloudflared-servicemonitor.yaml
> +    - port: 44483
```suggestion
    - port: 'metrics'
```

when I test this PR on my local machine, it should use the name of port instead of use port directly

2024-10-17 03:18 UTC, STRRL commented on helm/cloudflare-tunnel-ingress-controller/templates/controlled-cloudflared-connector-headless-service.yaml
> +    strrl.dev/cloudflare-tunnel-ingress-controller: controlled-cloudflared-connector
updated in be107bd

2024-10-17 09:25 UTC, z0rc commented on helm/cloudflare-tunnel-ingress-controller/templates/controlled-cloudflared-servicemonitor.yaml
> +    - port: 44483
Quotes aren't needed here, so I'll add commit without them. Thanks for the suggestion.

2024-10-23 04:28 UTC, STRRL commented
awesome! I am going to test it on my local machine manually, and I think this pr would be merged soon!

2024-10-23 04:49 UTC, merged