Update `Service.status.loadBalancer.ingress` when reconciling
STRRL/cloudflare-tunnel-ingress-controller pull request #69
Opened 2024-01-07 21:08 UTC by UnstoppableMango

Should resolve #68

2024-01-19 10:58 UTC, STRRL requested changes
Hi @UnstoppableMango , thanks for your contributions! Before this PR get merged, there is something needs changes:

- the field to be updated is `ingress.Status.LoadBalancer.Ingress`, not `service.Status.LoadBalancer.Ingress`. ref: https://github.com/tailscale/tailscale/blob/1c3c3d6752314c802007fd8f223e0c8bbddb7984/cmd/k8s-operator/ingress.go#L270-L281
- we should update ingress **after** we actually put rules on cloudflare, that's really import for kubernetes controller pattern. In other words, the codes need to be inserte at here: https://github.com/STRRL/cloudflare-tunnel-ingress-controller/blob/12fe1c8ebdd68095b33d1a61ce696b20b428a9c4/pkg/controller/ingress-controller.go#L101

2024-01-19 14:44 UTC, UnstoppableMango commented
You got it! That first one is a little embarrassing 😳 should be able to make the updates this afternoon!

2024-01-19 20:59 UTC, UnstoppableMango commented on pkg/controller/ingress-controller.go
> +			Hostname: i.tunnelClient.TunnelDomain(),
In the original comment in #68 they mentioned using the cloudflare cname value, do you agree with this? Or should this use the ingress hostname?

Also, should `https://` be appended to the beginning?

2024-01-19 21:00 UTC, UnstoppableMango commented
Ach I apoligize that first attempt was really half-baked!

I didn't see a great spot to move tests to, is there a place you think they should live?

2024-03-28 03:08 UTC, blade2005 commented
> Ach I apoligize that first attempt was really half-baked!
> 
> I didn't see a great spot to move tests to, is there a place you think they should live?

@STRRL pinging you on this as I think it may have been missed. 

I'd love to see this get merged, I'll admit I don't know go and got confused reading everything.

2024-05-08 10:17 UTC, STRRL commented on pkg/controller/ingress-controller.go
> +			Hostname: i.tunnelClient.TunnelDomain(),
Hi @UnstoppableMango , sorry for the late response.

we do not need `https://` prefix.

2024-05-08 10:20 UTC, merged